//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTorrents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieTorrents.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前电脑不是监视电脑，不能启动。.
        /// </summary>
        internal static string BtCurrentPcIsNotMonitor {
            get {
                return ResourceManager.GetString("BtCurrentPcIsNotMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在查询中，稍后重试。.
        /// </summary>
        internal static string BTIsWorking {
            get {
                return ResourceManager.GetString("BTIsWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eye32 {
            get {
                object obj = ResourceManager.GetObject("Eye32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EyeStop32 {
            get {
                object obj = ResourceManager.GetObject("EyeStop32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoBlue32 {
            get {
                object obj = ResourceManager.GetObject("InfoBlue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoGree32 {
            get {
                object obj = ResourceManager.GetObject("InfoGree32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoRed32 {
            get {
                object obj = ResourceManager.GetObject("InfoRed32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoYellow32 {
            get {
                object obj = ResourceManager.GetObject("InfoYellow32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请只勾选一项作为要拷贝豆瓣信息的原始项！.
        /// </summary>
        internal static string TextCheckOnlyOneItem {
            get {
                return ResourceManager.GetString("TextCheckOnlyOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认拷贝豆瓣信息到所选记录？.
        /// </summary>
        internal static string TextConfirmCopDoubanInfo {
            get {
                return ResourceManager.GetString("TextConfirmCopDoubanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定删除勾选的记录？
        ///选择是同时删除文件
        ///否仅删除记录.
        /// </summary>
        internal static string TextConfirmDelete {
            get {
                return ResourceManager.GetString("TextConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录监视中.
        /// </summary>
        internal static string TextDirInMonitor {
            get {
                return ResourceManager.GetString("TextDirInMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录监视停止.
        /// </summary>
        internal static string TextDirMonitorStopped {
            get {
                return ResourceManager.GetString("TextDirMonitorStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功移动{0}条记录。
        ///{1}.
        /// </summary>
        internal static string TextFilesMoved {
            get {
                return ResourceManager.GetString("TextFilesMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功重命名{0}条记录。
        ///{1}.
        /// </summary>
        internal static string TextFilesRenamed {
            get {
                return ResourceManager.GetString("TextFilesRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件夹不存在:\r\n{0}.
        /// </summary>
        internal static string TextFolderNotExists {
            get {
                return ResourceManager.GetString("TextFolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string TextHint {
            get {
                return ResourceManager.GetString("TextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载了{0} 个文件，{1} 已知项目。.
        /// </summary>
        internal static string TextLoadNFiles {
            get {
                return ResourceManager.GetString("TextLoadNFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有勾选任何记录！.
        /// </summary>
        internal static string TextNoCheckedItems {
            get {
                return ResourceManager.GetString("TextNoCheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有搜索到任何结果.
        /// </summary>
        internal static string TextNoResultsFound {
            get {
                return ResourceManager.GetString("TextNoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 种子文件根目录没有配置.
        /// </summary>
        internal static string TextNoRootFolder {
            get {
                return ResourceManager.GetString("TextNoRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有选择任何记录！.
        /// </summary>
        internal static string TextNoSelectedItems {
            get {
                return ResourceManager.GetString("TextNoSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}文件夹下有子文件夹！.
        /// </summary>
        internal static string TextPathHasChildDirectory {
            get {
                return ResourceManager.GetString("TextPathHasChildDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录 {0} 下有大量的文件，确认转移？.
        /// </summary>
        internal static string TextPathHavePlentyFiles {
            get {
                return ResourceManager.GetString("TextPathHavePlentyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择的目录必须是种子文件目录&quot;{0}&quot;的子目录！.
        /// </summary>
        internal static string TextPathMustInRoot {
            get {
                return ResourceManager.GetString("TextPathMustInRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录&quot;{0}&quot;不存在！.
        /// </summary>
        internal static string TextPathNotExists {
            get {
                return ResourceManager.GetString("TextPathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 种子文件根目录&quot;{0}&quot;不存在！.
        /// </summary>
        internal static string TextRootFolderNotExists {
            get {
                return ResourceManager.GetString("TextRootFolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一个正确的目录.
        /// </summary>
        internal static string TextSelectCorrectFolder {
            get {
                return ResourceManager.GetString("TextSelectCorrectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择除源项以外的更多项操作！.
        /// </summary>
        internal static string TextSelectItemsExcludeSource {
            get {
                return ResourceManager.GetString("TextSelectItemsExcludeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在执行其他操作，等待完成后操作.
        /// </summary>
        internal static string TextWaitOtherOperation {
            get {
                return ResourceManager.GetString("TextWaitOtherOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定取消当前操作?.
        /// </summary>
        internal static string TxtConfirmCancelCurrentOperation {
            get {
                return ResourceManager.GetString("TxtConfirmCancelCurrentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件 {0} 不存在!.
        /// </summary>
        internal static string TxtFileNotExists {
            get {
                return ResourceManager.GetString("TxtFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载了0 个文件，0 已知项目。.
        /// </summary>
        internal static string TxtLoadZeroFiles {
            get {
                return ResourceManager.GetString("TxtLoadZeroFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 种子目录[{0}].
        /// </summary>
        internal static string TxtSeedRottDir {
            get {
                return ResourceManager.GetString("TxtSeedRottDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动监视.
        /// </summary>
        internal static string TxtStartDirMonitor {
            get {
                return ResourceManager.GetString("TxtStartDirMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止监视.
        /// </summary>
        internal static string TxtStopDirMonitor {
            get {
                return ResourceManager.GetString("TxtStopDirMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在执行其他操作，等待完成后操作.
        /// </summary>
        internal static string TxtWaitForOtherOperation {
            get {
                return ResourceManager.GetString("TxtWaitForOtherOperation", resourceCulture);
            }
        }
    }
}
