//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0dayUnrar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_0dayUnrar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定停止操作.
        /// </summary>
        internal static string TextConfirmStop {
            get {
                return ResourceManager.GetString("TextConfirmStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的文件夹不能时源文件夹的子目录.
        /// </summary>
        internal static string TextDestSourceSame {
            get {
                return ResourceManager.GetString("TextDestSourceSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要解压的目的文件路径.
        /// </summary>
        internal static string TextSelectDestFolder {
            get {
                return ResourceManager.GetString("TextSelectDestFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要解压的源文件路径.
        /// </summary>
        internal static string TextSelectSourceFolder {
            get {
                return ResourceManager.GetString("TextSelectSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        internal static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束.
        /// </summary>
        internal static string TextStop {
            get {
                return ResourceManager.GetString("TextStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot close the program now.
        ///Please wait the process finish..
        /// </summary>
        internal static string TextWaitFinish {
            get {
                return ResourceManager.GetString("TextWaitFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
